#!/usr/bin/env bash
# add server host

# locate dir of sync-deploy tool
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

setting="$DIR/syn-setting"

#---- Option Setting
while getopts :u:d:p:h opt
do case "$opt" in
	u) hostname=$OPTARG ;;
	d) hostip=$OPTARG ;;
    p) hostport=$OPTARG ;;
	h)  echo
		echo "Usage: sync-hostadd -u host_name -d host_ip -p host_port"
		echo ">>> examples:"
		echo "              sync-hostadd -u wangshx -d 10.15.22.110 -p 22"
        echo
        exit ;;
	*) echo "Unknown option: $opt"
		echo
		sync-hostadd -h
        exit ;;
	esac
done

# if hostname is not set, show help info
if [ ! -n "$hostname" ]; then
	sync-hostadd -h
	exit
fi

# if hostip is not set, show help info
if [ ! -n "$hostip" ]; then
	sync-hostadd -h
	exit
fi

# if hostport is not set, set 22 as default
if [ ! -n "$hostport" ]; then
	hostport=22
    echo "host port not set, default 22 wii be assigned."
fi

#----- Host Add
hostadd="$hostname,$hostip,$hostport"

isgrep=`grep $hostadd $DIR/sync-hosts`

#echo $hostadd
#echo $isgrep

if [ -z $isgrep ]; then
    echo $hostadd >> $DIR/sync-hosts
    echo "host add done."
else
    echo "host already exists, please check."
    echo "exit..."
fi